# Generated by Django 6.0.1 on 2026-02-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0002_remove_project_tag_project_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
