# Generated by Django 6.0.1 on 2026-02-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0003_contactdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
